#!/usr/bin/env python

import ws
import http.server
import socketserver
import json

class CoiotServer(http.server.SimpleHTTPRequestHandler):
    def __init__(self, request, client_address, server):
        self.ws = ws.CoiotWs()
        super(CoiotServer, self).__init__(request, client_address, server)

    def ws_get(self):
        response = json.dumps(self.ws.get(self.path)).encode('utf-8')

        if response == None:
            self.send_response(204)
            self.end_headers()
        else:
            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.send_header("Content-length", len(response))
            self.end_headers()
            self.wfile.write(response)

    def ws_set(self):
        r = self.rfile.read(int(self.headers.get("Content-Length"))).decode('utf-8')
        self.ws.set(self.path, json.loads(r))
        self.send_response(204)
        self.end_headers()

    def do_GET(self):
        self.path = self.path.replace("../", "")
        if self.path.replace("/", "") == "":
            self.path = "/html/index.html"
        elif self.path.startswith("/img/"):
            pass
        elif self.path.startswith("/ws/"):
            self.ws_get()
            return
        else:
            self.send_error(404)
            return
        super(CoiotServer, self).do_GET()

    def do_PUT(self):
        if self.path.startswith("/ws/"):
            self.ws_set()
            return
        super(CoiotServer, self).do_PUT()

if __name__ == "__main__":
    with http.server.HTTPServer(("", 8000), CoiotServer) as s:
        s.serve_forever()
